services:
  smartctl-exporter:
    image: prometheuscommunity/smartctl-exporter:latest
    container_name: smartctl-exporter
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
    user: root
    ports:
      - 9633:9633
    privileged: true
    volumes:
      - /run/udev:/run/udev:ro
      - /dev:/dev:ro
networks:
  default:
    external: true
    name: homenet