services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 0:0
    ports:
      - "4533:4533"
    restart: unless-stopped
    volumes:
      - "./data:/data"
      - "/mnt/media/flacs:/music:ro"