global:
  scrape_interval: 30s

scrape_configs:
  # NODE EXPORTERS (both machines in ONE job)
  - job_name: "node"
    static_configs:
      - targets: ["192.168.1.2:9100"]
        labels:
          instance: "home"

#      - targets: ["192.168.1.3:9100"]
#        labels:
#          instance: "worker"

  # CADVISOR (both machines)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          instance: "home"

#      - targets: ["192.168.1.3:8080"]
#        labels:
#          instance: "worker"


  # GPU (only worker)
 # - job_name: "gpu"
 #   static_configs:
 #     - targets: ["192.168.1.3:9400"]
 #       labels:
 #         instance: "worker"

  - job_name: process-exporter
    static_configs:
      - targets:
         - process-exporter:9256

  - job_name: smartctl
    static_configs:
      - targets:
         - smartctl-exporter:9633

  - job_name: zfs_exporter
    static_configs:
      - targets:
         - 192.168.1.2:9134
