services:
  process-exporter:
    image: ncabatoff/process-exporter:latest
    container_name: process-exporter
    restart: unless-stopped
    ports:
      - 9256:9256
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - ./:/config/:ro
    command:
      - --procfs=/host/proc
      - --config.path=/config/config.yml
networks:
  default:
    external: true
    name: homenet