services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    user: 911:911
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "44" # video (usually)
      - "992" # render
    volumes:
      - /dev/shm:/cache/transcodes
      - /opt/jellyfin/config:/config
      - /docker-cache/jellyfin/trickplay:/config/data/trickplay
      - /docker-cache/jellyfin/cache:/cache
      - /mnt/tank/movies:/movies
      - /mnt/tank/series:/series
      - /etc/localtime:/etc/localtime
    restart: unless-stopped
networks:
  default:
    external: true
    name: homenet
