services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=911
      - PGID=911
    volumes:
      - /etc/localtime:/etc/localtime
      - ./rdrconfig:/config
      - /mnt/tank/movies:/movies #optional
      - /downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=911
      - PGID=911
    volumes:
      - /etc/localtime:/etc/localtime
      - ./prwlrconfig:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - BROWSER_TIMEOUT=120000
    ports:
      - 8191:8191
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=911# Change to your user ID (e.g., 1000)
      - PGID=911# Change to your group ID
      - TZ=Asia/Kolkata # Change to your Timezone (e.g., Asia/Kolkata)
    volumes:
      - ./bazarr:/config
      - /mnt/tank/movies:/movies # Must match Radarr's movie path exactly
    ports:
      - 6767:6767
    restart: unless-stopped
networks:
  default:
    external: true
    name: homenet